rpmfusion-infra/fedy

plugins/neomutt.plugin/install.sh, plugins/neomutt.plugin/metadata.json
Signed-off-by: Malte Kiefer <malte.kiefer@mailbox.org>
=> added neomutt

plugins/throttled.plugin/install.sh, plugins/throttled.plugin/metadata.json, plugins/throttled.plugin/uninstall.sh
Workaround for Intel throttling issues in Linux with Lenovo notebooks.
=> added throttled

plugins/mongodb.plugin/install.sh, plugins/mongodb.plugin/metadata.json, plugins/mongodb.plugin/uninstall.sh
=> added MongoDB

plugins/waybar.plugin/install.sh, plugins/waybar.plugin/metadata.json, plugins/waybar.plugin/uninstall.sh
=> added waybar

plugins/anydesk.plugin/install.sh, plugins/anydesk.plugin/metadata.json, plugins/anydesk.plugin/uninstall.sh
=> fix anydesk installation and uninstallation

plugins/alacritty.plugin/install.sh, plugins/alacritty.plugin/metadata.json, plugins/alacritty.plugin/uninstall.sh
=> added alacritty

plugins/pamixer.plugin/install.sh, plugins/pamixer.plugin/metadata.json, plugins/pamixer.plugin/uninstall.sh
**Attention: new category, I will make later a second PR with other apps for that category**
=> added pamixer

plugins/azurecli.plugin/metadata.json, plugins/neomutt.plugin/metadata.json, plugins/onedrive.plugin/metadata.json
@kwizart moved apps to terminal apps
=> moved apps to terminal apps

plugins/tdiff.plugin/install.sh, plugins/tdiff.plugin/metadata.json, plugins/tdiff.plugin/uninstall.sh
=> added tdiff

plugins/photoflare.plugin/install.sh, plugins/photoflare.plugin/metadata.json, plugins/photoflare.plugin/uninstall.sh
=> added photoflare

plugins/crowtranslate.plugin/install.sh, plugins/crowtranslate.plugin/metadata.json, plugins/crowtranslate.plugin/uninstall.sh
=> added crow-translate

plugins/nushell.plugin/install.sh, plugins/nushell.plugin/metadata.json, plugins/nushell.plugin/uninstall.sh
=> added nushell

plugins/intellijideacommunity.plugin/install.sh, plugins/intellijideaultimate.plugin/install.sh
=> Use cacerts from the system for IntelliJ

plugins/dbeaver.plugin/install.sh, plugins/dbeaver.plugin/metadata.json, plugins/dbeaver.plugin/uninstall.sh
=> added dbeaver

plugins/gitfiend.plugin/install.sh, plugins/gitfiend.plugin/metadata.json, plugins/gitfiend.plugin/uninstall.sh
=> added GitFiend

plugins/wike.plugin/install.sh, plugins/wike.plugin/metadata.json, plugins/wike.plugin/uninstall.sh
=> added Wike

plugins/blanket.plugin/install.sh, plugins/blanket.plugin/metadata.json, plugins/blanket.plugin/uninstall.sh
=> added blanket

plugins/githubcli.plugin/install.sh, plugins/githubcli.plugin/metadata.json, plugins/githubcli.plugin/uninstall.sh
Adicionei essa nova ferramenta cli do github
=> add github cli

plugins/tailscale.plugin/install.sh, plugins/tailscale.plugin/metadata.json, plugins/tailscale.plugin/uninstall.sh
=> added tailscale

plugins/mullvadvpn.plugin/install.sh, plugins/mullvadvpn.plugin/metadata.json, plugins/mullvadvpn.plugin/uninstall.sh
=> added mullvad vpn
